namespace Capital.Core.Enums
{
    [Flags]
    public enum Symbol : byte
    {
        /// <summary>
        /// Australia 200: Australia's leading stock market index
        /// </summary>
        AU200 = 0,

        DE30 = 11,
        ES35 = 12,
        EU50 = 13,
        FR40 = 25,
        HK50 = 32,
        JP225 = 33,
        UK100 = 41,
        US100 = 42,
        US30 = 43,
        US500 = 44,

        AUCUSD = 1,
        AUDCAD = 2,
        AUDCHF = 3,
        AUDJPY = 4,
        AUDNZD = 5,
        AUDUSD = 6,
        CADCHF = 7,
        CADJPY = 8,
        CHFJPY = 9,
        CNHJPY = 10,
        EUCUSD = 14,
        EURAUD = 15,
        EURCAD = 16,
        EURCHF = 17,
        EURCNH = 18,
        EURGBP = 19,
        EURHKD = 20,
        EURJPY = 21,
        EURNZD = 22,
        EURTRY = 23,
        EURUSD = 24,
        GBPAUD = 26,
        GBPCAD = 27,
        GBPCHF = 28,
        GBPJPY = 29,
        GBPNZD = 30,
        GBPUSD = 31,
        JPYUSD = 34,
        NZDCAD = 35,
        NZDCHF = 36,
        NZDJPY = 37,
        NZDUSD = 38,

        USDAUC = 45,
        USDAUCc = 46,
        USDAUD = 47,
        USDBRL = 48,
        USDCAD = 49,
        USDCHF = 50,
        USDCNH = 51,
        USDEUCc = 52,
        USDEUR = 53,
        USDGBP = 54,
        USDHKD = 55,
        USDJPY = 56,
        USDMXN = 57,
        USDSGD = 58,
        USDTRY = 59,
        USDUSC = 60,
        USDUSCc = 61,
        USDZAR = 62,
        XBRUSD = 69,
        XNGUSD = 70,

        XAGEUR = 63,
        XAGUSD = 64,
        XAUAUD = 65,
        XAUEUR = 66,
        XAUGBP = 67,
        XAUUSD = 68,
        Palladium = 39,
        Platinum = 40,
    }
}